version: '3'
services:
  web:
    image: hacklab/mapasculturais-nginx:latest
    restart: always
    volumes:
     - ./docker-data/public-files:/var/www/html/files
     - ./docker-data/assets:/var/www/html/assets
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais


  mapasculturais:
    env_file:
      - .env
    build:
      context: ./
      dockerfile: compose/production/Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./docker-data/assets:/var/www/html/assets
      - ./docker-data/public-files:/var/www/html/files
      - ./docker-data/private-files:/var/www/private-files
      - ./docker-data/saas-files:/var/www/SaaS
    links:
      - db
      - redis
    environment:
      #- ACTIVE_THEME=MeuTema

      - LOG_LEVEL=DEBUG
      - LOG_ENABLED=true
      
      - APP_MODE=production
      - APP_LCODE=pt_BR
      - BUILD_ASSETS=1
#      - APP_LCODE=pt_BR,es_ES # para selecao do idioma baseado no navegador
      
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://redis:6379
      - PENDING_PCACHE_RECREATION_INTERVAL=5

      - DB_PASSWORD=mapas
      - DB_USER=mapas
      - DB_DB=mapas
      - DB_VERSION
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru
    restart: always
    
      
  db:
    image: postgis/postgis:14-master
    restart: always
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
      - POSTGRES_DB_TEST=mapasculturais_test
      - TZ=GMT+3
      - PGTZ=GMT+3
#    ports:
#      - "5432:5432"
    volumes:
      - ./compose/db:/docker-entrypoint-initdb.d
      - ./docker-data/db-data:/var/lib/postgresql/data
